!set variable_substitution=true;
!set exit_on_error=true;

--  Destino: MODEL.CM - "Dominio de negocio"
--  Fuentes: ENT_&{P_ENVIRONMENT}_CURATED_DB.CM.CM_DETAILOFFER
--  Reprocesable : Si
--  Descripcion  : Agrega regsitros unicos

-- Parameters:
SET V_CODPAIS = '&{P_CODPAIS}';
SET P_MODULO = '&{P_MODULO}';
SET P_ENVIRONMENT = '&{P_ENVIRONMENT}';
SET P_IDCARGA = '&{P_IDCARGA}';
SET P_IDCABECERABITACORA = '&{P_IDCABECERABITACORA}';
SET P_INICIO_MODULO = '&{P_INICIO_MODULO}'; 
SET P_UUID_PROCESS = '&{P_UUID_PROCESS}';
SET P_UUIDFILE = '&{P_UUIDFILE}';

-- Procedure:
/* TO DO */

-- =========================================
--  CREACION DE TABLAS TEMPORALES
--  ----------------------------------------
-- =========================================

CREATE OR REPLACE TEMPORARY TABLE LOCAL_DOMINIO_CM_DETAILOFFER (
    INPUTORIGINCODE VARCHAR(3),
    FLAGTACTIC VARCHAR(1),
    FLAGOBLIGATORIO NUMBER(1,0),
    FORMATCODE VARCHAR(1),
    FORMATCODEDSS VARCHAR(1),
    COMENTARIO VARCHAR(40),
    CODVENTA VARCHAR(6),
    CUCPADRE VARCHAR(11),
    CUCOFERTAPADRE VARCHAR(11),
    CUCOFERTAPADREDSS VARCHAR(11),
    CUC VARCHAR(11),
    CODSAP VARCHAR(9),
    PRECIONORMALMN NUMBER(15,5),
    PRECIOOFERTAMN NUMBER(15,5),
    DISCOUNTPERCENTAGETEMINATION NUMBER(15,5),
    SETCOST NUMBER(15,5),
    OFFERID NUMBER(7,0),
    FLAGGAINMATERIAL VARCHAR(10),
    COMPOUNDVARIABLE NUMBER(1,0),
    QUADFACTOR NUMBER(2,0),
    OFFERORIGINID NUMBER(5,0),
    ANIOCAMPANA VARCHAR(6),
    CODPAIS VARCHAR(2),
    SCENARIOID NUMBER(5,0),
    CODVENTAPADRE VARCHAR(6),
    REACTIONCANDIDATEID NUMBER(6, 0),
    CREATEDDATESIMULATIONREACTION VARCHAR(30),
    ODDCANDIDATEID NUMBER(6,0),
    AGRUPADORATO VARCHAR(2),
    REPETITIONFACTOR NUMBER(2,0),
    MARCAOFERTA VARCHAR(6),
    CATEGORIAOFERTA VARCHAR(20),
    TIPOOFERTA VARCHAR(70),
    LINEAOFERTA VARCHAR(40),
    IDCARGA VARCHAR(12) ,
	UUIDFILE VARCHAR(36) ,
    PRIMARY KEY(CODPAIS, ANIOCAMPANA, OFFERID, CODVENTA, CODSAP)
);

-- =========================================
--  INICIO DE LÓGICA DE NEGOCIO
--  ----------------------------------------
-- =========================================

INSERT INTO LOCAL_DOMINIO_CM_DETAILOFFER (
    INPUTORIGINCODE,
    FLAGTACTIC,
    FLAGOBLIGATORIO,
    FORMATCODE,
    FORMATCODEDSS,
    COMENTARIO,
    CODVENTA,
    CUCPADRE,
    CUCOFERTAPADRE,
    CUCOFERTAPADREDSS,
    CUC,
    CODSAP,
    PRECIONORMALMN,
    PRECIOOFERTAMN,
    DISCOUNTPERCENTAGETEMINATION,
    SETCOST,
    OFFERID,
    FLAGGAINMATERIAL,
    COMPOUNDVARIABLE,
    QUADFACTOR,
    OFFERORIGINID,
    ANIOCAMPANA,
    CODPAIS,
    SCENARIOID,
    CODVENTAPADRE,
    REACTIONCANDIDATEID,
    CREATEDDATESIMULATIONREACTION,
    ODDCANDIDATEID,
    AGRUPADORATO,
    REPETITIONFACTOR,
    MARCAOFERTA,
    CATEGORIAOFERTA,
    TIPOOFERTA,
    LINEAOFERTA,
    IDCARGA,
    UUIDFILE
    )
SELECT
    INPUTORIGINCODE,
    FLAGTACTIC,
    FLAGOBLIGATORIO,
    FORMATCODE,
    FORMATCODEDSS,
    COMENTARIO,
    CODVENTA,
    CUCPADRE,
    CUCOFERTAPADRE,
    CUCOFERTAPADREDSS,
    CUC,
    CODSAP,
    PRECIONORMALMN,
    PRECIOOFERTAMN,
    DISCOUNTPERCENTAGETEMINATION,
    SETCOST,
    OFFERID,
    FLAGGAINMATERIAL,
    COMPOUNDVARIABLE,
    QUADFACTOR,
    OFFERORIGINID,
    ANIOCAMPANA,
    CODPAIS,
    SCENARIOID,
    CODVENTAPADRE,
    REACTIONCANDIDATEID,
    CREATEDDATESIMULATIONREACTION,
    ODDCANDIDATEID,
    AGRUPADORATO,
    REPETITIONFACTOR,
    MARCAOFERTA,
    CATEGORIAOFERTA,
    TIPOOFERTA,
    LINEAOFERTA,
    '&{P_IDCARGA}'  AS IDCARGA, 
    '&{P_UUID_PROCESS}' AS UUIDFILE
FROM ENT_&{P_ENVIRONMENT}_CURATED_DB.CM.CM_DETAILOFFER
WHERE CODPAIS = $V_CODPAIS AND
      UUIDFILE = $P_UUIDFILE;

-- =========================================
--  LLAMADO AL SP_LOAD_DOMAIN_TABLE
--  ----------------------------------------
-- =========================================

CALL ENT_&{P_ENVIRONMENT}_COMMON_DB.ETL_OBJECTS.SP_LOAD_DOMAIN_TABLE (
    $P_ENVIRONMENT,
    $P_MODULO ,
    $V_CODPAIS ,
    $P_IDCABECERABITACORA ,
    $P_INICIO_MODULO,
    $P_IDCARGA,
    $P_UUID_PROCESS,
    'LOCAL_DOMINIO_CM_DETAILOFFER',
    'AAN_CM_Detailoffer'
);