!set variable_substitution=true;
!set exit_on_error=true;

--  Destino: MODEL.CM - "Dominio de negocio"
--  Fuentes: ENT_&{P_ENVIRONMENT}_CURATED_DB.CM.CM_HANDLEPARAMETERS
--  Reprocesable : Si
--  Descripcion  : Agrega regsitros unicos

-- Parameters:
SET V_CODPAIS = '&{P_CODPAIS}';
SET P_MODULO = '&{P_MODULO}';
SET P_ENVIRONMENT = '&{P_ENVIRONMENT}';
SET P_IDCARGA = '&{P_IDCARGA}';
SET P_IDCABECERABITACORA = '&{P_IDCABECERABITACORA}';
SET P_INICIO_MODULO = '&{P_INICIO_MODULO}'; 
SET P_UUID_PROCESS = '&{P_UUID_PROCESS}';
SET P_UUIDFILE = '&{P_UUIDFILE}';

-- Procedure:
/* TO DO */

-- =========================================
--  CREACION DE TABLAS TEMPORALES
--  ----------------------------------------
-- =========================================

CREATE OR REPLACE TEMPORARY TABLE LOCAL_DOMINIO_CM_HANDLEPARAMETERS (
    SCENARIOID NUMBER(5,0),
    DESTESCENARIO VARCHAR(20),
    CODPAIS VARCHAR(2),
    ANIOCAMPANA VARCHAR(6),
    CODIGOPALANCA VARCHAR(3),
    FLAGTACTIC VARCHAR(1),
    FLAGOBLIGATORIO VARCHAR(1),
    DESBOLSA VARCHAR(15),
    QUANTITYOFFERSEVENT NUMBER(2,0),
    REACTIONCANDIDATEID NUMBER(6,0),
    CREATEDDATESIMULATIONREACTION VARCHAR(30),
    ODDCANDIDATEID VARCHAR(10),
    IDCARGA VARCHAR(12) ,
	UUIDFILE VARCHAR(36) ,
    PRIMARY KEY(CODPAIS, ANIOCAMPANA,CODIGOPALANCA, SCENARIOID, FLAGTACTIC, FLAGOBLIGATORIO, DESBOLSA, ODDCANDIDATEID)
);

-- =========================================
--  INICIO DE LÓGICA DE NEGOCIO
--  ----------------------------------------
-- =========================================

INSERT INTO LOCAL_DOMINIO_CM_HANDLEPARAMETERS (
    SCENARIOID,
    DESTESCENARIO,
    CODPAIS,
    ANIOCAMPANA,
    CODIGOPALANCA,
    FLAGTACTIC,
    FLAGOBLIGATORIO,
    DESBOLSA,
    QUANTITYOFFERSEVENT,
    REACTIONCANDIDATEID,
    CREATEDDATESIMULATIONREACTION,
    ODDCANDIDATEID,
    IDCARGA,
    UUIDFILE
    )
SELECT
    SCENARIOID,
    DESTESCENARIO,
    CODPAIS,
    ANIOCAMPANA,
    CODIGOPALANCA,
    FLAGTACTIC,
    FLAGOBLIGATORIO,
    DESBOLSA,
    QUANTITYOFFERSEVENT,
    REACTIONCANDIDATEID,
    CREATEDDATESIMULATIONREACTION,
    ODDCANDIDATEID,
    '&{P_IDCARGA}'  AS IDCARGA, 
    '&{P_UUID_PROCESS}' AS UUIDFILE
FROM ENT_&{P_ENVIRONMENT}_CURATED_DB.CM.CM_HANDLEPARAMETERS
WHERE CODPAIS = $V_CODPAIS AND
      UUIDFILE=$P_UUIDFILE;

-- =========================================
--  LLAMADO AL SP_LOAD_DOMAIN_TABLE
--  ----------------------------------------
-- =========================================

CALL ENT_&{P_ENVIRONMENT}_COMMON_DB.ETL_OBJECTS.SP_LOAD_DOMAIN_TABLE (
    $P_ENVIRONMENT,
    $P_MODULO ,
    $V_CODPAIS ,
    $P_IDCABECERABITACORA ,
    $P_INICIO_MODULO,
    $P_IDCARGA,
    $P_UUID_PROCESS,
    'LOCAL_DOMINIO_CM_HANDLEPARAMETERS',
    'AAN_CM_Handleparameters'
);
