!set variable_substitution=true;
!set exit_on_error=true;

--  Destino: MODEL.CM - "Dominio de negocio"
--  Fuentes: ENT_&{P_ENVIRONMENT}_CURATED_DB.CM.CM_DETAILEVENT
--  Reprocesable : Si
--  Descripcion  : Agrega regsitros unicos

-- Parameters:

SET V_CODPAIS = '&{P_CODPAIS}';
SET P_MODULO = '&{P_MODULO}';
SET P_ENVIRONMENT = '&{P_ENVIRONMENT}';
SET P_IDCARGA = '&{P_IDCARGA}';
SET P_IDCABECERABITACORA = '&{P_IDCABECERABITACORA}';
SET P_INICIO_MODULO = '&{P_INICIO_MODULO}'; 
SET P_UUID_PROCESS = '&{P_UUID_PROCESS}';
SET P_UUIDFILE = '&{P_UUIDFILE}';

-- Procedure:
/* TO DO */

-- =========================================
--  CREACION DE TABLAS TEMPORALES
--  ----------------------------------------
-- =========================================

CREATE OR REPLACE TEMPORARY TABLE LOCAL_DOMINIO_CM_DETAILEVENT (
    CODPAIS VARCHAR(2),
    ANIOCAMPANA VARCHAR(6),
    CODIGOPALANCA VARCHAR(3), 
    INICIOEVENTO VARCHAR(10),
    FINEVENTO VARCHAR(10),
    DESCRIPCIONEVENTO VARCHAR(12),
    COMENTARIOEVENTO VARCHAR(22),
    FLAGEVENTOOCULTO VARCHAR(1),
    SCENARIOID NUMBER(5,0),
    REACTIONCANDIDATEID VARCHAR(30),
    CREATEDDATESIMULATIONREACTION VARCHAR(30),
    REACTIONFLAG VARCHAR(1),
    PRIORIDADEVENTO NUMBER(2,0),
    IDCARGA VARCHAR(12) ,
	UUIDFILE VARCHAR(36) ,
    PRIMARY KEY(CODPAIS, ANIOCAMPANA, CODIGOPALANCA)
);

-- =========================================
--  INICIO DE LÓGICA DE NEGOCIO
--  ----------------------------------------
-- =========================================

INSERT INTO LOCAL_DOMINIO_CM_DETAILEVENT (
    CODPAIS,
    ANIOCAMPANA,
    CODIGOPALANCA,
    INICIOEVENTO,
    FINEVENTO,
    DESCRIPCIONEVENTO,
    COMENTARIOEVENTO,
    FLAGEVENTOOCULTO,
    SCENARIOID,
    REACTIONCANDIDATEID,
    CREATEDDATESIMULATIONREACTION,
    REACTIONFLAG,
    PRIORIDADEVENTO,
    IDCARGA,
    UUIDFILE
    )
SELECT
    CODPAIS,
    ANIOCAMPANA,
    CODIGOPALANCA,
    INICIOEVENTO,
    FINEVENTO,
    DESCRIPCIONEVENTO,
    COMENTARIOEVENTO,
    FLAGEVENTOOCULTO,
    SCENARIOID,
    REACTIONCANDIDATEID,
    CREATEDDATESIMULATIONREACTION,
    REACTIONFLAG,
    PRIORIDADEVENTO,
    '&{P_IDCARGA}'  AS IDCARGA, 
    '&{P_UUID_PROCESS}' AS UUIDFILE

FROM ENT_&{P_ENVIRONMENT}_CURATED_DB.CM.CM_DETAILEVENT
WHERE CODPAIS = $V_CODPAIS AND
      UUIDFILE = $P_UUIDFILE;

-- =========================================
--  LLAMADO AL SP_LOAD_DOMAIN_TABLE
--  ----------------------------------------
-- =========================================

CALL ENT_&{P_ENVIRONMENT}_COMMON_DB.ETL_OBJECTS.SP_LOAD_DOMAIN_TABLE (
    $P_ENVIRONMENT,
    $P_MODULO ,
    $V_CODPAIS ,
    $P_IDCABECERABITACORA ,
    $P_INICIO_MODULO,
    $P_IDCARGA,
    $P_UUID_PROCESS,
    'LOCAL_DOMINIO_CM_DETAILEVENT',
    'AAN_CM_Detailevent'
);