!set variable_substitution=true;
!set exit_on_error=true;

--  Destino: MODEL.CM - "Dominio de negocio"
--  Fuentes: ENT_&{P_ENVIRONMENT}_CURATED_DB.CM.CM_PARAMETERSOFFERPRODUCTS
--  Reprocesable : Si
--  Descripcion  : Agrega regsitros unicos

-- Parameters:
SET V_CODPAIS = '&{P_CODPAIS}';
SET P_MODULO = '&{P_MODULO}';
SET P_ENVIRONMENT = '&{P_ENVIRONMENT}';
SET P_IDCARGA = '&{P_IDCARGA}';
SET P_IDCABECERABITACORA = '&{P_IDCABECERABITACORA}';
SET P_INICIO_MODULO = '&{P_INICIO_MODULO}'; 
SET P_UUID_PROCESS = '&{P_UUID_PROCESS}';
SET P_UUIDFILE = '&{P_UUIDFILE}';

-- Procedure:
/* TO DO */

-- =========================================
--  CREACION DE TABLAS TEMPORALES
--  ----------------------------------------
-- =========================================

CREATE OR REPLACE TEMPORARY TABLE LOCAL_DOMINIO_CM_PARAMETERSOFFERPRODUCTS (
    SCENARIOID NUMBER(5,0),
    DESTESCENARIO VARCHAR(11),
    CODPAIS VARCHAR(2),
    ANIOCAMPANA VARCHAR(6),
    CODIGOPALANCA VARCHAR(3),
    OFFERPARAMETERID NUMBER(5,0),
    FLAGTACTIC VARCHAR(1),
    QUANTITYOFFERSPARAMETER NUMBER(1,0),
    DESCRIPTIONTACTIC VARCHAR(10),
    PRINCIPALBRAND VARCHAR(6),
    PRINCIPALCATEGORY VARCHAR(20),
    PRINCIPALTYPE VARCHAR(37),
    PRINCIPALLINE VARCHAR(26),
    PRINCIPALPRODUCT VARCHAR(15),
    ROLLINGSEGMENT VARCHAR(255),
    PURCHASEGROUP VARCHAR(255),
    DESREGION VARCHAR(255),
    DESZONA VARCHAR(255),
    REACTIONCANDIDATEID NUMBER(6,0),
    ODDCANDIDATEID NUMBER(6,0),
    IDCARGA VARCHAR(12),
	UUIDFILE VARCHAR(36),
    PRIMARY KEY(CODPAIS, ANIOCAMPANA,CODIGOPALANCA, OFFERPARAMETERID)
);

-- =========================================
--  INICIO DE LÓGICA DE NEGOCIO
--  ----------------------------------------
-- =========================================

INSERT INTO LOCAL_DOMINIO_CM_PARAMETERSOFFERPRODUCTS (
    SCENARIOID,
    DESTESCENARIO,
    CODPAIS,
    ANIOCAMPANA,
    CODIGOPALANCA,
    OFFERPARAMETERID,
    FLAGTACTIC,
    QUANTITYOFFERSPARAMETER,
    DESCRIPTIONTACTIC,
    PRINCIPALBRAND,
    PRINCIPALCATEGORY,
    PRINCIPALTYPE,
    PRINCIPALLINE,
    PRINCIPALPRODUCT,
    ROLLINGSEGMENT,
    PURCHASEGROUP,
    DESREGION,
    DESZONA,
    REACTIONCANDIDATEID,
    ODDCANDIDATEID,
    IDCARGA,
    UUIDFILE
    )
SELECT
    SCENARIOID,
    DESTESCENARIO,
    CODPAIS,
    ANIOCAMPANA,
    CODIGOPALANCA,
    OFFERPARAMETERID,
    FLAGTACTIC,
    QUANTITYOFFERSPARAMETER,
    DESCRIPTIONTACTIC,
    PRINCIPALBRAND,
    PRINCIPALCATEGORY,
    PRINCIPALTYPE,
    PRINCIPALLINE,
    PRINCIPALPRODUCT,
    ROLLINGSEGMENT,
    PURCHASEGROUP,
    DESREGION,
    DESZONA,
    REACTIONCANDIDATEID,
    ODDCANDIDATEID,
    '&{P_IDCARGA}'  AS IDCARGA, 
    '&{P_UUID_PROCESS}' AS UUIDFILE
FROM ENT_&{P_ENVIRONMENT}_CURATED_DB.CM.CM_PARAMETERSOFFERPRODUCTS
WHERE CODPAIS = $V_CODPAIS AND
      UUIDFILE=$P_UUIDFILE;

-- =========================================
--  LLAMADO AL SP_LOAD_DOMAIN_TABLE
--  ----------------------------------------
-- =========================================

CALL ENT_&{P_ENVIRONMENT}_COMMON_DB.ETL_OBJECTS.SP_LOAD_DOMAIN_TABLE (
    $P_ENVIRONMENT,
    $P_MODULO ,
    $V_CODPAIS ,
    $P_IDCABECERABITACORA ,
    $P_INICIO_MODULO,
    $P_IDCARGA,
    $P_UUID_PROCESS,
    'LOCAL_DOMINIO_CM_PARAMETERSOFFERPRODUCTS',
    'AAN_CM_Parametersofferproducts'
);