!set variable_substitution=true;
!set exit_on_error=true;

--  Destino: MODEL.CM - "Dominio de negocio"
--  Fuentes: ENT_&{P_ENVIRONMENT}_CURATED_DB.CM.CM_HANDLEOFFERCONSULTANT
--  Reprocesable : Si
--  Descripcion  : Agrega regsitros unicos

-- Parameters:
SET V_CODPAIS = '&{P_CODPAIS}';
SET P_MODULO = '&{P_MODULO}';
SET P_ENVIRONMENT = '&{P_ENVIRONMENT}';
SET P_IDCARGA = '&{P_IDCARGA}';
SET P_IDCABECERABITACORA = '&{P_IDCABECERABITACORA}';
SET P_INICIO_MODULO = '&{P_INICIO_MODULO}'; 
SET P_UUID_PROCESS = '&{P_UUID_PROCESS}';
SET P_UUIDFILE = '&{P_UUIDFILE}';

-- Procedure:
/* TO DO */

-- =========================================
--  CREACION DE TABLAS TEMPORALES
--  ----------------------------------------
-- =========================================

CREATE OR REPLACE TEMPORARY TABLE LOCAL_DOMINIO_CM_HANDLEOFFERCONSULTANT (
    CODPAIS VARCHAR(2),
    ANIOCAMPANA VARCHAR(6),
    CODEBELISTA VARCHAR(10),
    CODIGOPALANCA VARCHAR(3),
    OFFERID NUMBER(10,0),
    ORDEN NUMBER(10,0),
    SCENARIOID NUMBER(10,0),
    REACTIONCANDIDATEID NUMBER(10,0),
    CREATEDDATESIMULATIONREACTION VARCHAR(30),
    ODDCANDIDATEID NUMBER(10,0),
    DIA VARCHAR(10),
    REACTIONFLAG NUMBER(10,0),
    FLAGMEDIODEVENTA VARCHAR(10),
    IDCARGA VARCHAR(12) ,
	UUIDFILE VARCHAR(36) ,
    PRIMARY KEY(CODPAIS, ANIOCAMPANA,CODEBELISTA, CODIGOPALANCA, OFFERID, DIA)
);

-- =========================================
--  INICIO DE LÓGICA DE NEGOCIO
--  ----------------------------------------
-- =========================================

INSERT INTO LOCAL_DOMINIO_CM_HANDLEOFFERCONSULTANT (
    CODPAIS,
    ANIOCAMPANA,
    CODEBELISTA,
    CODIGOPALANCA,
    OFFERID,
    ORDEN,
    SCENARIOID,
    REACTIONCANDIDATEID,
    CREATEDDATESIMULATIONREACTION,
    ODDCANDIDATEID,
    DIA,
    REACTIONFLAG,
    FLAGMEDIODEVENTA,
    IDCARGA,
    UUIDFILE
    )
SELECT
    CODPAIS,
    ANIOCAMPANA,
    CODEBELISTA,
    CODIGOPALANCA,
    OFFERID,
    ORDEN AS "ORDER",
    SCENARIOID,
    REACTIONCANDIDATEID,
    CREATEDDATESIMULATIONREACTION,
    ODDCANDIDATEID,
    DIA AS "DAY",
    REACTIONFLAG,
    FLAGMEDIODEVENTA,
    '&{P_IDCARGA}'  AS IDCARGA, 
    '&{P_UUID_PROCESS}' AS UUIDFILE
FROM ENT_&{P_ENVIRONMENT}_CURATED_DB.CM.CM_HANDLEOFFERCONSULTANT
WHERE CODPAIS = $V_CODPAIS AND
      UUIDFILE = $P_UUIDFILE;

-- =========================================
--  LLAMADO AL SP_LOAD_DOMAIN_TABLE
--  ----------------------------------------
-- =========================================

CALL ENT_&{P_ENVIRONMENT}_COMMON_DB.ETL_OBJECTS.SP_LOAD_DOMAIN_TABLE (
    $P_ENVIRONMENT,
    $P_MODULO ,
    $V_CODPAIS ,
    $P_IDCABECERABITACORA ,
    $P_INICIO_MODULO,
    $P_IDCARGA,
    $P_UUID_PROCESS,
    'LOCAL_DOMINIO_CM_HANDLEOFFERCONSULTANT',
    'AAN_CM_Handleofferconsultant'
);